config/routes.rb
Rails.application.routes.draw do
  resources :brands
  devise_for :users
  root to: 'welcome#index'

  resources :brands
  resources :builds

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  include Sluggable
  validates :title, presence: true
  mount_uploader :logo, LogoUploader
end

app/models/build.rb
class Build < ApplicationRecord
  include Sluggable
  validates :title, presence: true, length: { maximum: 250 }
end

app/models/concerns/sluggable.rb
module Sluggable
  extend ActiveSupport::Concern
  included do
    before_validation :set_default_slug
  end

  def set_default_slug
    return if slug.present?
    self.slug = Russian
      .translit(title)
      .tr(' ', '-')
      .gsub(/[^\x00-\x7F]+/, '')
      .gsub(/[^\w_ \-]+/i, '')
      .gsub(/[ \-]+/i, '-')
      .gsub(/^\-|\-$/i, '').downcase if title.present?
  end

  def to_param
    "#{id}-#{slug}"
  end
end

app/models/concerns/taggable.rb
module Taggable
  extend ActiveSupport::Concern
  included do
    has_many :taggings, dependent: :destroy, as: :taggable
    has_many :tags, through: :taggings

    attr_accessor :tag_line
    after_save :saving_tags, if: :tags?
  end

  def tag_list
    tags.map(&:name).join(' ')
  end

  def saving_tags
    self.tags = tag_line.split(' ').map do |tag|
      Tag.find_or_create_by(name: tag.strip.downcase)
    end
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).builds
  end

  def self.search(query)
    joins(:tag).where(name: query)
  end

  private
  def tags?
    tag_line.present?
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :taggables, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :taggable, polymorphic: true
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable, :trackable#, :confirmable
  mount_uploader :avatar, AvatarUploader

  has_many :builds

  validates_processing_of :avatar
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  def admin?
    return false unless roles.present?
    roles.include?('admin')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_sanitized_params, if: :devise_controller?

  protected

  def configure_sanitized_params
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :name, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:email, :name, :avatar, :remove_avatar, :password, :password_confirmation,
                                                           :current_password)
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  def index
    @brands = scope.all
  end

  def show
  end

  def new
    @brand = Brand.new
    render 'edit'
  end

  def edit
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      redirect_to @brand, notice: t('.brand_created')
    else
      render 'edit'
    end
  end

  def update
    if @brand.update(brand_params)
      redirect_to @brand, notice: t('.brand_updated')
    else
      render :edit
    end
  end

  def destroy
    # @brand.destroy
    redirect_to brands_url, notice: t('.brand_deleted')
  end

  private

  def scope
    Brand
  end

  def set_brand
    @brand = Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:title, :logo, :site)
  end
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @builds = scope.all#.page(params[:page])
  end

  def show
    @build = scope.find(params[:id])
  end

  def destroy
    @build = edit_scope.find(params[:id])
    redirect_to @build, notice: t('.build_deleted')
  end

  def new
    @build = current_user.builds.build
    render 'edit'
  end

  def create
    @build = current_user.builds.build(build_params)
    if @build.save
      redirect_to @build, notice: t('.build_created')
    else
      render 'edit'
    end
  end

  def edit
    @build = edit_scope.find(params[:id])
  end

  def update
    @build = edit_scope.find(params[:id])
    if @build.update(build_params)
      redirect_to @build, notice: t('.build_updated')
    else
      render 'edit'
    end
  end

  private

  def edit_scope
    return Build.none unless user_signed_in?
    return Build if current_user.admin?
    current_user.builds
  end

  def scope
    Build
  end

  def build_params
    params[:build].permit!
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.order('created_at DESC')
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update(tag_params)
      redirect_to tags_path
    else
      render 'edit'
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to tags_path
  end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper

  def bootstrap_devise_error_messages!
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    count = pluralize(resource.errors.count, "error")
    html = <<-HTML
    <div class="alert alert-danger">
      The form contains #{count}:
      #{messages}
    </div>
    HTML
    html.html_safe if resource.errors.any?
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def avatar_for(user, options = { size: 80 })
    return image_tag(user.avatar.thumb, alt: user.name, class: "avatar") if user.avatar.present?
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "avatar")
	end

end

app/views/application/_footer.html.haml
%footer
  %ul.nav.navbar-nav
    %li.nav-item= link_to t('.about'), '#', class: 'nav-link'
  %small
    = t('.copyright', year: Time.now.year)

app/views/application/_header.html.haml
%nav.navbar.navbar-dark.bg-inverse.navbar-fixed-top
  = image_tag 'drone.png', alt: t('.logo-alt'), title: t('.brand'), size: '40x40', class: 'navbar-brand'
  = link_to t('.brand'), root_url, class: 'navbar-brand'
  - if user_signed_in?
    %ul.nav.navbar-nav
      %li{ class: ['nav-item', "#{'active' if controller_name == 'builds'}"] }
        = link_to t('.builds'), builds_path, class: 'nav-link'
      %li{ class: ['nav-item', "#{'active' if controller_name == 'brands'}"] }
        = link_to t('.brands'), brands_path, class: 'nav-link'
      - if current_user.admin?
        %li.nav-item= link_to 'Items', '#', class: 'nav-link'
    %ul.nav.navbar-nav.pull-xs-right
      -#
        = form_tag '#', class: 'form-inline' do
          = text_field_tag :query, params[:query], class: 'form-control', placeholder: t('.search')
          = submit_tag t('.search_btn'), class: 'btn btn-success'
      %li.nav-item= link_to t('.profile'), edit_user_registration_path, class: 'nav-link'
      %li.nav-item= link_to t('.sign_out'), destroy_user_session_path,  class: 'nav-link', method: :delete
  - else
    %ul.nav.navbar-nav
      %li.nav-item= link_to t('.features'), '#', class: 'nav-link'
    %ul.nav.navbar-nav.pull-xs-right
      %li.nav-item= link_to t('.sign_up'), new_user_registration_path, class: 'nav-link'
      %li.nav-item= link_to t('.sign_in'), new_user_session_path,      class: 'nav-link'

app/views/brands/edit.html.haml
%h1
  - if @brand.persisted?
    = t '.form_title_edit'
  - else
    = t '.form_title_new'

= form_for @brand do |f|
  - if @brand.errors.any?
    #error_explanation
      %h2= "#{pluralize(@brand.errors.count, "error")} prohibited this brand from being saved:"
      %ul
        - @brand.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :logo
    = f.text_field :logo
  .field
    = f.label :site
    = f.text_field :site
  .actions
    = f.submit 'Save'


= link_to 'Show', @brand
\|
= link_to 'Back', brands_path

app/views/brands/index.html.haml
%h1= t('.title')

%table
  %thead
    %tr
      %th Title
      %th Logo
      %th Site
      %th
      %th
      %th

  %tbody
    - @brands.each do |brand|
      %tr
        %td= brand.title
        %td= brand.logo
        %td= brand.site
        %td= link_to 'Show', brand
        %td= link_to 'Edit', edit_brand_path(brand)
        %td= link_to 'Destroy', brand, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to t('add'), new_brand_path

app/views/brands/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @brand.title
%p
  %b Logo:
  = @brand.logo
%p
  %b Site:
  = @brand.site

= link_to 'Edit', edit_brand_path(@brand)
\|
= link_to 'Back', brands_path

app/views/builds/_build.html.haml
%tr
  %td= link_to build.title, [build]

app/views/builds/_form.html.haml
=form_for @build do |f|
  - if @build.errors.any?
    #error_explanation
      %h2= "#{pluralize(@build.errors.count, "error")} prohibited this build from being saved:"
      %ul
        - @build.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title

  .field
    = f.label :tag_line, "Tags (separated by spaces)"
    - if @build.tag_list.empty?
      = f.text_field :tag_line
    - else
      = f.text_field :tag_line, value: @build.tag_list

  .field
    = f.label :description
    = f.text_area :description

  .actions
    = f.submit 'Save'

app/views/builds/edit.html.haml
%h1
  - if @build.persisted?
    = t '.form_title_edit'
  - else
    = t '.form_title_new'
= form_for @build do |f|
  - if @build.errors.any?
    %ul
      - @build.errors.full_messages.each do |error|
        %li= error
  = f.text_field :title
  %br
  = f.text_area :description
  = f.submit t('submit')

app/views/builds/index.html.haml
%h1= t '.title'
= link_to t('add'), new_build_path
%table.table
  = render @builds
=# paginate @builds

app/views/builds/new.html.haml
%h3 New Build
= render 'form'

app/views/builds/show.html.haml
%h4= @build.title
%p
  Tags:
  %strong= raw @build.tags.map(&:name).map { |t| link_to t, tagname_path(t) }.join(' ')
%p
  Description:
  =@build.description

%p= link_to 'Edit', edit_build_path(@build)

app/views/builds/withtag.html.haml
%h3
  Tag:
  = @tagname
-@builds.each do |build|
  %p
    %strong= link_to build.title, build

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no'}
    %meta{'http-equiv': 'x-ua-compatible', content: 'ie=edge'}
    %title Dronny
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    .container
      = render 'header'
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield
      = render 'footer'
      = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/tags/_form.html.haml
=form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this build from being saved:"
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name

  .actions
    = f.submit 'Save'

app/views/tags/edit.html.haml
%h4
  Edit
  = @tag.name
= render 'form'

app/views/tags/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Tag

  %tbody
    -@tags.each do |tag|
      %tr
        %td= tag.name
        %td= link_to 'Edit', edit_tag_path(tag)
        %td= link_to 'Delete', tag_path(tag), method: :delete, data: { confirm: "Are you sure?" }

app/views/welcome/index.html.haml
= provide(:title, 'Welcome')
.jumbotron
  %h1= t('.jumbotitle')
  %h4= t('.jumbosubtitle')
  = link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-lg'
.row
  .col-sm-4 Awesome feature one
  .col-sm-4 Awesome feature two
  .col-sm-4 Awesome feature three